name: MysticalGear
main: me.endureblackout.UtopiaGear.UtopiaGear
version: 1.0
api: 1.15
description: Stronger armor
author: [EndureBlackout]
commands:
  mg:
    description: Main MysticalGear command.
  duel:
    description: MysticalGear duel command.

